"""Profile fix 1 - To init with registration

Revision ID: 061736006319
Revises: db98ac1c03a0
Create Date: 2024-08-30 17:29:52.549095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061736006319'
down_revision: Union[str, None] = 'db98ac1c03a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Profile', 'profile_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Profile', 'profile_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
