"""Profile fix 1 - Nullable for img

Revision ID: 17c0d3b540b0
Revises: 190040b74282
Create Date: 2024-09-02 12:29:26.576613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c0d3b540b0'
down_revision: Union[str, None] = '190040b74282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Profile', 'profile_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Profile', 'profile_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
