"""Models fix 2 - Aded Email + Max length of some strings

Revision ID: a729d8855bfe
Revises: c6dec8d7005a
Create Date: 2024-09-01 15:42:21.851953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a729d8855bfe'
down_revision: Union[str, None] = 'c6dec8d7005a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email')
    # ### end Alembic commands ###
