"""Base migration

Revision ID: db98ac1c03a0
Revises: 
Create Date: 2024-08-30 13:57:42.616786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db98ac1c03a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('profile_info', sa.String(), nullable=True),
    sa.Column('profile_hobbies', sa.String(), nullable=True),
    sa.Column('profile_interest', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_from', sa.Integer(), nullable=False),
    sa.Column('profile_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_from'], ['Profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_to'], ['Profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_from', sa.Integer(), nullable=False),
    sa.Column('profile_to', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(), nullable=False),
    sa.Column('comment_media_img', sa.String(), nullable=True),
    sa.Column('comment_media_sound', sa.String(), nullable=True),
    sa.Column('comment_media_video', sa.String(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_from'], ['Profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_to'], ['Profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_from', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('message_media_img', sa.String(), nullable=True),
    sa.Column('message_media_sound', sa.String(), nullable=True),
    sa.Column('message_media_video', sa.String(), nullable=True),
    sa.Column('message_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['Chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_from'], ['Profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    op.drop_table('Comment')
    op.drop_table('Chat')
    op.drop_table('Profile')
    op.drop_table('User')
    # ### end Alembic commands ###
