"""Chat fix 1 - Added nullable chat name

Revision ID: e8feb3870e52
Revises: 17c0d3b540b0
Create Date: 2024-09-02 14:19:31.723040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8feb3870e52'
down_revision: Union[str, None] = '17c0d3b540b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('chat_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat', 'chat_name')
    # ### end Alembic commands ###
